from .ldap_exception import LDAPConnectionError
